### ISSUE TITLE
Create basic functionality.

### ISSUE THREAD

**Issue by brian-guerrero** [brian-guerrero/homebase#2]
- [x] Install and setup Firebase.
- [x] Add form control to not submit on blank fields
- [x] Add confirmation modal/message when user submits form
- [x] Add functionality for user to upload images
- [x] Add mapping and map markers for listings
- [x] Clear form / re-route on submit
- [x] Turn off autocomplete on past entries
- [x] add autocomplete for address via google map api

**Comment by lgearen0528** [comment]
- [x]  Add form control to not submit on blank fields
- [ ] Add confirmation modal/message when user submits form
- [ ] Add functionality for user to upload images
- [ ] Add mapping and map markers for listings
- [ ] Clear form / re-route on submit
- [ ] Turn off autocomplete on past entries
- [ ] add autocomplete for address via google map api
